# Calamares — bootloader module
---
efiBootLoader:      "grub"
grubInstall:        "grub-install"
grubMkconfig:       "grub-mkconfig"
grubCfg:            "/boot/grub/grub.cfg"
grubProbe:          "grub-probe"
efiDirectory:       "/boot/efi"
efiBootloaderId:    "INSOMNIA"
installEFIFallback: true

# GRUB theme — OLED black
# See: archiso/airootfs/usr/share/grub/themes/insomnia/
#grubTheme:        "/usr/share/grub/themes/insomnia/theme.txt"
