# Calamares — displaymanager module
---
displaymanagers:
    - gdm
    - sddm
    - lightdm

defaultDesktopEnvironment:
    executable: "gnome-session"
    desktopFile: "gnome"

# Enable autologin in installed system? No — user sets this.
autologinUser: ""
