# Calamares — services-systemd module
---
units:
    - name: tlp
      enabled: true
    - name: NetworkManager
      enabled: true
    - name: acpid
      enabled: true
    - name: insomnia-init
      enabled: true
    - name: gdm
      enabled: true
    - name: bluetooth
      enabled: false
    - name: avahi-daemon
      enabled: false
