# Calamares — users module
---
defaultGroups:
    - name: users
      state: create
    - name: lp
      state: skip
    - name: video
      state: skip
    - name: network
      state: skip
    - name: storage
      state: skip
    - name: wheel
      state: skip
    - name: audio
      state: skip

autologinGroup:   autologin
sudoersGroup:     wheel

# Shell for new users
userShell: /bin/zsh

# Default hostname prefix
hostnameAction: "none"
hostname: "insomnia"

setRootPassword: true
doAutologin:     false
doReusePassword: true

passwordRequirements:
    minLength: 8
    maxLength: -1
    libpwquality:
        - minlen=8
