# Insomnia System — pacman.conf
# /etc/pacman.conf

[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
ILoveCandy
CheckSpace
VerbosePkgLists
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# Insomnia custom repository (highest priority — listed first)
[insomnia]
Server = https://ProgrammerKrot.github.io/insomnia-repo/x86_64
SigLevel = Required DatabaseOptional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
