# Insomnia System — pacman.conf
# /etc/pacman.conf

[options]
HoldPkg     = pacman glibc
Architecture = auto
Color
ILoveCandy
CheckSpace
VerbosePkgLists
ParallelDownloads = 5
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

# Enable after hosting insomnia-repo (see docs/REPO-HOSTING.md)
# [insomnia]
# Server = https://ProgrammerKrot.github.io/insomnia-repo/x86_64
# SigLevel = Required DatabaseOptional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
