# Insomnia System — Calamares main configuration
# /etc/calamares/settings.conf

---
modules-search: [ local, /usr/lib/calamares/modules ]

# Installation sequence — in order of execution
sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - luksbootkeyfile
    - luksopenswaphookcfg
    - initcpiocfg
    - initcpio
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - services-systemd
    - packages
    - grubcfg
    - bootloader
    - shellprocess@post
    - umount
  - show:
    - finished

branding: insomnia
prompt-install: true
dont-chroot: false
oem-setup: false
disable-cancel: false
disable-cancel-during-exec: true
hide-back-and-next-during-exec: true
quit-at-end: false
